config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
    get '/login',   to: 'registrations#new'
    post '/login',   to: 'registrations#create'
    delete '/logout',  to: 'registrations#destroy'
  
  resources :users do
    resources :gossips
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  attr_accessor :login
  
  has_many :gossips
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: {with: /\A[a-zA-Z0-9 _\/]*\z/}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup

  if login = conditions.delete(:login)
    where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
  else
    where(conditions.to_hash).first
end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

  before_action :configure_devise_parameters, if: :devise_controller?

protected 

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password)}
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
def index
    @gossips = Gossip.all
    @user= User.find(params[:user_id])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @gossip=Gossip.find(params[:id])
    @user= @gossip.user(params[:username])
  end

  # GET /users/new
  def new
    @gossip = Gossip.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.user = current_user
    @gossip.save
    redirect_to "/users/#{current_user.id}/gossips"
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user=User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/index.html.erb
<h1>Gossip Library</h1>
<%=link_to "Lancer ta Rumeur", new_user_gossip_path(current_user.id), class: "btn btn-dark" %>
<p> <% @gossips.each do |gossip| %>
<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <h5 class="card-title"><%=gossip.content%></h5>
    <p class="card-text"><%= gossip.user.username %></p>


    <% if current_user.id == gossip.user_id %> 
    <p ><%= link_to "Voir la Rumeur", user_gossip_path(current_user.id, gossip.id), class: "btn btn-dark" %>
    	<%= link_to "Éditer", edit_user_gossip_path(current_user.id, gossip.id), class: "btn btn-dark" %>
    	<%= link_to "Taire la rumeur", user_gossip_path(current_user.id, gossip.id), class: "btn btn-dark", :data => {:confirm => 'Voulez-vous taire la rumeur?', :method => "DELETE"} %>
    <% end %>
  </div>
</div>   
<br>
<%end %> 

app/views/gossips/new.html.erb
<div class="container">
<h1></h1>
  <div class="center jumbotron">
<div class="form-group">
<%= form_for @gossip, url: {action: "create"} do |f| %>
    Le titre de ta rumeur:
    <%= f.text_field :title, class: 'form-control' %><br>
    Ta rumeur:
    <%= f.text_area :content, class: 'form-control' %><br>
    <%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>
</div>
</div>
</div>

app/views/gossips/show.html.erb
<div class="card">
  <div class="card-header">
    Oh le joli gossip! t'es une vraie chippie toi !!
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer"> <cite title="Source Title"><%= @gossip.user %></cite></footer>
    </blockquote>
  </div>
</div>
<br>
  <%=link_to "Index des Gossips", gossips_path, class: "btn btn-dark" %>
  <%=link_to "Éditer ton Gossip", edit_gossip_path, class: "btn btn-dark" %>
    <%=link_to "Écrire une Rumeur", new_gossip_path, class: "btn btn-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipClubbbbb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  
  <body>
  <div class="container">
  <%= render 'shared/nav' %>
  <%= render 'shared/alerts'%>


    <%= yield %>  </div>

  </body>
</html>

app/views/shared/_alerts.html.erb
<p class="notice" ><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand h1" href="/"><kbd>GOSSIP CLUB</kbd></a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 text-secondary">

  <% if current_user %>
        <li class="nav-item active text-secondary" ><p class="nav-link"><kbd><%= link_to "Accueil", root_path %></kbd></p></li>
        <li class="nav-item"><p class="nav-link"><kbd><%= link_to "Gossip Library", user_gossips_path(current_user.id) %></kbd></p></li>
        <li class="nav-item" ><p class="nav-link"><kbd><%= link_to "Nouveau gossip", new_user_gossip_path(current_user.id) %></kbd></p></li>
      </ul>
    <div class="nav-item">
      <p class="nav-link"><kbd><%= link_to "L0G 0UT /", destroy_user_session_path, method: :delete %>   <%= link_to "/ Edit Account", edit_user_registration_path %></kbd></p>
        
  <% else %>

  <% end %>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
    </nav>
      <br>

</header>

app/views/static_pages/home.html.erb
	<div class="center jumbotron">
      <%= image_tag('gossip.png', width:"430", class:"rounded float-right")%>

  <% if current_user %>
  <h1>Tu es bien sur ton profil :)</h1>
  <h3>
    As-tu un secret ? </h3><br>
  	<%= link_to "Écrire un nouveau gossip", new_user_gossip_path(current_user.id), class: "btn btn-lg btn-info" %>
  	<%= link_to "Voir les derniers gossips", user_gossips_path(current_user.id), class: "btn btn-lg btn-info" %>

  <% else %>
    <h1>Bienvenue au beau pays des secrets</h1>
  <h3>
    Ici, tu peux diffuser les plus belles rumeurs  🎓  
  </h3><br>
  <%= link_to "s'identifier", new_user_session_path, class: "btn btn-lg btn-info" %>
  <%= link_to "s'inscrire", new_user_registration_path, class: "btn btn-lg btn-info" %>

  <% end %>
</div>

app/views/users/_form.html.erb
  <div class="center jumbotron">

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Pseudo</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pseudo:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>